services:
  - type: web
    name: bible-course-app
    runtime: node
    plan: free
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildCommand: yarn install
